dist: xenial
language: node_js

node_js:
- '8'

env:
- WORKING_DIR=notary-api SKIP_AUDIT=true SKIP_TESTS=true
- WORKING_DIR=notary-signing-service SKIP_AUDIT=true SKIP_TESTS=true

cache:
  directories:
  - "$WORKING_DIR/node_modules"

before_install: npm i -g npm@6.1.0

install:
- cd $WORKING_DIR
- npm install

before_script:
  - npm run lint
  - npm audit || $SKIP_AUDIT
  - npm run test:coverage || $SKIP_TESTS
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info || $SKIP_TESTS

script: npm run build

before_deploy: npm run publish

deploy:
  provider: releases
  api-key:
    secure: L8X5s3Na0e8+CZYH54IBjFqmBsOZZ3wPeemLxqYEqQZxBmAtafT1q4DO2c5REpmDX4lUKXCTIBDrCg67ufsfN5UEMN9cXGoQF6YZ9BAgUqc8EzlzszzkvgDZCIH2dtxBC3gexAUOtOIdtht8Uq2td0eeuZ+iTKFOudDADLrkxyOS991wq3g+10O+C/9fpiaV0EZb9xabyZRKfe2Q9SdxrrWubrsfQhzYvPoBmC6aixlAr3jj8eREi2Uo9U/muEtuT/adLCI5gv50WGTm5TqHvcTxVmXMcubIdT6CeEzQMinzRBtxjmCWX4QUvw/HB2fklv92WvnDKikaV90FzDl62GG3ek4KBwpAu+jfyYRxFmw7tkTO46l9pkyZ6JITbfnuUnGl4tjcyWofMg6GsMR1ygGkQBwKQI3HThQf6Aj/EoMjnjLIlVJyriV2Y3PJaf5YesUNGqaRxOUUAb/MpL+F5nc46XWEOiFpakMPlxdazGnrPRVVBvsoTxImLYPlkTBSs5oUDwANK+dgL5KT8Lf7hyrr8cYWJvfsuChtgowOxwV2JJj8gAVnl01qZvUH7DiLSAf8aUxSybD+RBlSoq2Jt6LZ8x/HtYKc9RUUS6w3DsGzliwg11outHC9f0dlaSP6Tf2EJRlSL6kADVZ7RpLvNvuNFgr7S83jqY9maSHzEb4=
  file_glob: true
  file: "artifacts/*.tar.gz"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - secure: U9zB79sOrY5XAHDMzoc6A5vYuFfuVz2SKnFejm0lnOZ/HLGS59k7Fxso4vJcjIj0LPw8tpR2khgs1VhOwsI/4KHr6AhXROdsD058vNk45/1+Q7BiWstUIIs0fxLsvPZDLLRakVd0tJKtupyzns7Bi9yemH83KD/V4C//zGBoF8Wiu0rCIMDxcDTTYqLIFQxFsXyNzTJC+XjYq+RzPJ5y27by2bJ+7PJq7vDZNlPmLcSvaH/CpkDu6RVYj3h787cXGblCL0n7QG9HnK8z6GWfqXPcpuqCF7X6TY6BYhHBBhZ8G8bi4u36c8oql1k1UY/wCoq0fq5Yh80dbUrOZpQ1O+h8XBpj4JQq7cgYWCrsBp9ceF5pn2ioZIDJrzu0OzGUHIoGuWC27Vysfjojgq+3bKo6aHA8qxQKTbfTip9gZE814GAcm97w1vNEOpWxdEkKsVKoCTMnZdzCj91YBSyAqx0+xCuLlAUhvg9kDwKXksCBvQ/nSU8zaRF3/YvRWyiTSMdDaTnaVULHQ8vN727H0oriLL++8M4XVgNynKY5Ot0a6GzEk2TJtK2tZhfExogZ82XQEkYdOJvqW1gxFAsG7GtHiwhRMoR5regT6dvD5+OiR+ncW5cBSzKuKGiUzykz6n7XQXspVQahiTSFJRFVRaNZCWyoiMF2oZ/HcBQjoCE=
    on_success: change
    on_failure: change
